### ISSUE TITLE
Allow livestreaming without Internet Access

### ISSUE THREAD

**Issue by stress-ins** [gopro/OpenGoPro#315]
**Is your feature request related to a problem or use case? Please describe.**
Use case -  I want live streaming to local RTMP in LOCAL wi-fi (without internet access), but I Can`t connect to wi-fi.

**Describe the solution you'd like**
I want go pro can connect and live streaming without internet access.

**Describe alternatives you've considered**
Add to wifi internet access, but when i turn off internet - go pro shutdown live stream and stop write video to SD

**Comment by stress-ins** [comment]
#227  - maybe duplicated. But I try GoPro Quick APP and API call - it`s not work in step connect to WIFI access point.
And stop record video when connect to internet down.

**Comment by mahboobkarimian** [comment]
I can confirm this statement with hero9.

> #227 - maybe duplicated. But I try GoPro Quick APP and API call - it`s not work in step connect to WIFI access point. And stop record video when connect to internet down.

**Comment by mahboobkarimian** [comment]
Indeed it looks for api.gopro.com, and probably it does a TCP/TLS handshake.
I tried to put this address in hosts, but this didn't help.

**Comment by soraxas** [comment]
Hi, I am experiencing the same thing. My GoPro Hero 11 can connect to a router that has WAN connection, but if I unplug WAN (and hence the router only has LAN), my GoPro refuse to connect to the router. 

This is true regardless of initiating the connection via the Android App, or via QR code command.

**Comment by SergejJurecko** [comment]
Are there any plans to fix this? This prevents integrating GoPro with an android app in any kind of user friendly way. Since you can only programmatically start hotspots on android without internet.

**Comment by tcamise-gpsw** [comment]
This is going to be supported in the next Hero 13 release.

**Comment by tcamise-gpsw** [comment]
This should be fixed as of Hero 13 Black v 2.0.0

**Comment by RexTech46** [comment]
I think it is not fixed. I try to connect to a local Wifi without an internet access. Using a Hero13 with labs firmware but it does not connect to the network using the app or QR codes.

**Comment by tcamise-gpsw** [comment]
You're correct. There is actually a new protobuf property that needs to be set. I'll update the docs.

**Comment by tcamise-gpsw** [comment]
Docs have been updated. There is a new [bypass_eula_check](https://gopro.github.io/OpenGoPro/ble/protocol/protobuf.html#requestconnectnew) field in the `RequestConnectNew` protobuf message that must set to True in order to allow connecting to a network without internet access.

**Comment by demiantres** [comment]
When I use ``bypass_eula_check`` then the Hero 13 (latest official firmware) refuses to go into live streaming mode (even if the router is connected to the internet).
